# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: sensor.proto
# Protobuf Python Version: 4.25.2
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0csensor.proto\"\x93\x02\n\x0bSensorFrame\x12\x11\n\ttimestamp\x18\x01 \x01(\x04\x12\x13\n\x0btemperature\x18\x02 \x01(\x02\x12\x10\n\x08pressure\x18\x03 \x01(\x02\x12\x0f\n\x07\x61\x63\x63_h_x\x18\x04 \x01(\x02\x12\x0f\n\x07\x61\x63\x63_h_y\x18\x05 \x01(\x02\x12\x0f\n\x07\x61\x63\x63_h_z\x18\x06 \x01(\x02\x12\x0f\n\x07\x61\x63\x63_i_x\x18\x07 \x01(\x02\x12\x0f\n\x07\x61\x63\x63_i_y\x18\x08 \x01(\x02\x12\x0f\n\x07\x61\x63\x63_i_z\x18\t \x01(\x02\x12\x0f\n\x07rot_i_x\x18\n \x01(\x02\x12\x0f\n\x07rot_i_y\x18\x0b \x01(\x02\x12\x0f\n\x07rot_i_z\x18\x0c \x01(\x02\x12\x0f\n\x07mag_i_x\x18\r \x01(\x02\x12\x0f\n\x07mag_i_y\x18\x0e \x01(\x02\x12\x0f\n\x07mag_i_z\x18\x0f \x01(\x02\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'sensor_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_SENSORFRAME']._serialized_start=17
  _globals['_SENSORFRAME']._serialized_end=292
# @@protoc_insertion_point(module_scope)
