# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: lib/storage/proto/state.proto
# Protobuf Python Version: 4.25.2
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1dlib/storage/proto/state.proto\"\xcc\x02\n\nStateFrame\x12\x11\n\ttimestamp\x18\x01 \x01(\x04\x12\x14\n\x0c\x66light_phase\x18\x02 \x01(\r\x12\r\n\x05pos_n\x18\x03 \x01(\x02\x12\r\n\x05pos_e\x18\x04 \x01(\x02\x12\r\n\x05pos_d\x18\x05 \x01(\x02\x12\r\n\x05vel_n\x18\x06 \x01(\x02\x12\r\n\x05vel_e\x18\x07 \x01(\x02\x12\r\n\x05vel_d\x18\x08 \x01(\x02\x12\r\n\x05\x61\x63\x63_n\x18\t \x01(\x02\x12\r\n\x05\x61\x63\x63_e\x18\n \x01(\x02\x12\r\n\x05\x61\x63\x63_d\x18\x0b \x01(\x02\x12\r\n\x05vel_x\x18\x0c \x01(\x02\x12\r\n\x05vel_y\x18\r \x01(\x02\x12\r\n\x05vel_z\x18\x0e \x01(\x02\x12\r\n\x05\x61\x63\x63_x\x18\x0f \x01(\x02\x12\r\n\x05\x61\x63\x63_y\x18\x10 \x01(\x02\x12\r\n\x05\x61\x63\x63_z\x18\x11 \x01(\x02\x12\x10\n\x08orient_x\x18\x12 \x01(\x02\x12\x10\n\x08orient_y\x18\x13 \x01(\x02\x12\x10\n\x08orient_z\x18\x14 \x01(\x02\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'lib.storage.proto.state_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_STATEFRAME']._serialized_start=34
  _globals['_STATEFRAME']._serialized_end=366
# @@protoc_insertion_point(module_scope)
