# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: state.proto
# Protobuf Python Version: 4.25.2
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0bstate.proto\"\xbd\x03\n\nStateFrame\x12\x11\n\ttimestamp\x18\x01 \x01(\x04\x12\x14\n\x0c\x66light_phase\x18\x02 \x01(\r\x12\x10\n\x08pos_vert\x18\x03 \x01(\x02\x12\x10\n\x08vel_vert\x18\x04 \x01(\x02\x12\x10\n\x08\x61\x63\x63_vert\x18\x05 \x01(\x02\x12\x11\n\tpos_geo_x\x18\x06 \x01(\x02\x12\x11\n\tpos_geo_y\x18\x07 \x01(\x02\x12\x11\n\tpos_geo_z\x18\x08 \x01(\x02\x12\x11\n\tvel_geo_x\x18\t \x01(\x02\x12\x11\n\tvel_geo_y\x18\n \x01(\x02\x12\x11\n\tvel_geo_z\x18\x0b \x01(\x02\x12\x11\n\tacc_geo_x\x18\x0c \x01(\x02\x12\x11\n\tacc_geo_y\x18\r \x01(\x02\x12\x11\n\tacc_geo_z\x18\x0e \x01(\x02\x12\x15\n\rangvel_body_x\x18\x10 \x01(\x02\x12\x15\n\rangvel_body_y\x18\x11 \x01(\x02\x12\x15\n\rangvel_body_z\x18\x12 \x01(\x02\x12\x15\n\rorientation_w\x18\x13 \x01(\x02\x12\x15\n\rorientation_x\x18\x14 \x01(\x02\x12\x15\n\rorientation_y\x18\x15 \x01(\x02\x12\x15\n\rorientation_z\x18\x16 \x01(\x02J\x04\x08\x0f\x10\x10\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'state_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_STATEFRAME']._serialized_start=16
  _globals['_STATEFRAME']._serialized_end=461
# @@protoc_insertion_point(module_scope)
