#include "storage.h"

// This file generated by ChatGPT

#include <inttypes.h>
#include <stdio.h>
#include <stdlib.h>

// Static FILE pointers to manage the CSV files internally
static FILE* sensor_csv_file = NULL;
static FILE* state_csv_file = NULL;

/**
 * @brief Creates a CSV file for SensorFrame data at the specified path and
 * writes the header row.
 *
 * @param file_path Path to the SensorFrame CSV file to be created.
 *                  Must be a null-terminated string.
 *
 * @return 0 on success, non-zero on failure.
 */
int create_sensor_csv(const char* file_path) {
    if (file_path == NULL) {
        fprintf(stderr, "Error: Sensor CSV file_path is NULL.\n");
        return -1;
    }

    // If a sensor CSV file is already open, close it before creating a new one
    if (sensor_csv_file != NULL) {
        fclose(sensor_csv_file);
        sensor_csv_file = NULL;
    }

    // Open the file in write mode (creates or overwrites the file)
    sensor_csv_file = fopen(file_path, "w");
    if (sensor_csv_file == NULL) {
        perror("Error opening Sensor CSV file for writing");
        return -2;
    }

    // Write the CSV header
    const char* header =
        "timestamp,temperature,pressure,"
        "acc_h_x,acc_h_y,acc_h_z,"
        "acc_i_x,acc_i_y,acc_i_z,"
        "rot_i_x,rot_i_y,rot_i_z,"
        "mag_i_x,mag_i_y,mag_i_z\n";

    if (fprintf(sensor_csv_file, "%s", header) < 0) {
        perror("Error writing Sensor CSV header");
        fclose(sensor_csv_file);
        sensor_csv_file = NULL;
        return -3;
    }

    return 0;
}

/**
 * @brief Appends a SensorFrame to the previously created SensorFrame CSV file
 * in CSV format.
 *
 * @param sensor_frame Pointer to the SensorFrame struct to be written.
 *                     Must not be NULL.
 *
 * @return 0 on success, non-zero on failure.
 */
int store_sensor_frame(const SensorFrame* sensor_frame) {
    if (sensor_frame == NULL) {
        fprintf(stderr, "Error: sensor_frame is NULL.\n");
        return -1;
    }

    if (sensor_csv_file == NULL) {
        fprintf(stderr,
                "Error: Sensor CSV file is not initialized. Call "
                "create_sensor_csv first.\n");
        return -2;
    }

    // Write the SensorFrame data in CSV format
    int result = fprintf(
        sensor_csv_file,
        "%" PRIu64
        ",%.2f,%.2f,"
        "%.3f,%.3f,%.3f,"
        "%.3f,%.3f,%.3f,"
        "%.2f,%.2f,%.2f,"
        "%.3f,%.3f,%.3f\n",
        sensor_frame->timestamp, sensor_frame->temperature,
        sensor_frame->pressure, sensor_frame->acc_h_x, sensor_frame->acc_h_y,
        sensor_frame->acc_h_z, sensor_frame->acc_i_x, sensor_frame->acc_i_y,
        sensor_frame->acc_i_z, sensor_frame->rot_i_x, sensor_frame->rot_i_y,
        sensor_frame->rot_i_z, sensor_frame->mag_i_x, sensor_frame->mag_i_y,
        sensor_frame->mag_i_z);

    if (result < 0) {
        perror("Error writing SensorFrame to CSV");
        return -3;
    }

    return 0;
}

/**
 * @brief Closes the SensorFrame CSV file if it's open.
 *        Should be called when done writing to ensure data is flushed and
 * resources are freed.
 *
 * @return 0 on success, non-zero on failure.
 */
int close_sensor_csv(void) {
    if (sensor_csv_file == NULL) {
        fprintf(stderr,
                "Warning: Sensor CSV file is already closed or was never "
                "opened.\n");
        return -1;
    }

    if (fclose(sensor_csv_file) != 0) {
        perror("Error closing Sensor CSV file");
        return -2;
    }

    sensor_csv_file = NULL;
    return 0;
}

/**
 * @brief Creates a CSV file for StateFrame data at the specified path and
 * writes the header row.
 *
 * @param file_path Path to the StateFrame CSV file to be created.
 *                  Must be a null-terminated string.
 *
 * @return 0 on success, non-zero on failure.
 */
int create_state_csv(const char* file_path) {
    if (file_path == NULL) {
        fprintf(stderr, "Error: State CSV file_path is NULL.\n");
        return -1;
    }

    // If a state CSV file is already open, close it before creating a new one
    if (state_csv_file != NULL) {
        fclose(state_csv_file);
        state_csv_file = NULL;
    }

    // Open the file in write mode (creates or overwrites the file)
    state_csv_file = fopen(file_path, "w");
    if (state_csv_file == NULL) {
        perror("Error opening State CSV file for writing");
        return -2;
    }

    // Write the CSV header
    const char* header =
        "timestamp,flight_phase,"
        "pos_vert,vel_vert,acc_vert,"
        "pos_geo_x,pos_geo_y,pos_geo_z,"
        "vel_geo_x,vel_geo_y,vel_geo_z,"
        "acc_geo_x,acc_geo_y,acc_geo_z,"
        "gentimestamp,"
        "angvel_body_x,angvel_body_y,angvel_body_z,"
        "orient_geo_w,orient_geo_x,orient_geo_y,orient_geo_z,"
        "pos_ekf,vel_ekf,acc_ekf,"
        "orient_ekf_w,orient_ekf_x,orient_ekf_y,orient_ekf_z,"
        "pos_var_ekf,vel_var_ekf,acc_var_ekf,"
        "orient_var_ekf_w,orient_var_ekf_x,orient_var_ekf_y,orient_var_ekf_z\n";

    if (fprintf(state_csv_file, "%s", header) < 0) {
        perror("Error writing State CSV header");
        fclose(state_csv_file);
        state_csv_file = NULL;
        return -3;
    }

    return 0;
}

/**
 * @brief Appends a StateFrame to the previously created StateFrame CSV file in
 * CSV format.
 *
 * @param state_frame Pointer to the StateFrame struct to be written.
 *                    Must not be NULL.
 *
 * @return 0 on success, non-zero on failure.
 */
int store_state_frame(const StateFrame* state_frame) {
    if (state_frame == NULL) {
        fprintf(stderr, "Error: state_frame is NULL.\n");
        return -1;
    }

    if (state_csv_file == NULL) {
        fprintf(stderr,
                "Error: State CSV file is not initialized. Call "
                "create_state_csv first.\n");
        return -2;
    }

    // Write the StateFrame data in CSV format
    int result = fprintf(
        state_csv_file,
        "%" PRIu64                // timestamp
        ",%u,"                    // flight_phase
        "%.2f,%.2f,%.2f,"         // *_vert
        "%.3f,%.3f,%.3f,"         // pos_geo_*
        "%.3f,%.3f,%.3f,"         // vel_geo_*
        "%.3f,%.3f,%.3f,"         // acc_geo_*
        "%" PRIu64                // gentimestamp
        ",%.3f,%.3f,%.3f,"        // angvel_body_*
        "%.4f,%.4f,%.4f,%.4f,"    // orient_geo_*
        "%.2f,%.2f,%.2f,"         // *_ekf
        "%.4f,%.4f,%.4f,%.4f,"    // orient_ekf_*
        "%.4f,%.4f,%.4f,"         // *_var_ekf
        "%.4f,%.4f,%.4f,%.4f\n",  // orient_var_ekf_*
        state_frame->timestamp, state_frame->flight_phase,
        state_frame->pos_vert, state_frame->vel_vert, state_frame->acc_vert,
        state_frame->pos_geo_x, state_frame->pos_geo_y, state_frame->pos_geo_z,
        state_frame->vel_geo_x, state_frame->vel_geo_y, state_frame->vel_geo_z,
        state_frame->acc_geo_x, state_frame->acc_geo_y, state_frame->acc_geo_z,
        state_frame->gentimestamp,  ///
        state_frame->angvel_body_x, state_frame->angvel_body_y,
        state_frame->angvel_body_z,  ///
        state_frame->orient_geo_w, state_frame->orient_geo_x,
        state_frame->orient_geo_y, state_frame->orient_geo_z,
        state_frame->pos_ekf, state_frame->vel_ekf, state_frame->acc_ekf,
        state_frame->orient_ekf_w, state_frame->orient_ekf_x,
        state_frame->orient_ekf_y, state_frame->orient_ekf_z,
        state_frame->pos_var_ekf, state_frame->vel_var_ekf,
        state_frame->acc_var_ekf,  ///
        state_frame->orient_var_ekf_w, state_frame->orient_var_ekf_x,
        state_frame->orient_var_ekf_y, state_frame->orient_var_ekf_z);

    if (result < 0) {
        perror("Error writing StateFrame to CSV");
        return -3;
    }

    return 0;
}

/**
 * @brief Closes the StateFrame CSV file if it's open.
 *        Should be called when done writing to ensure data is flushed and
 * resources are freed.
 *
 * @return 0 on success, non-zero on failure.
 */
int close_state_csv(void) {
    if (state_csv_file == NULL) {
        fprintf(
            stderr,
            "Warning: State CSV file is already closed or was never opened.\n");
        return -1;
    }

    if (fclose(state_csv_file) != 0) {
        perror("Error closing State CSV file");
        return -2;
    }

    state_csv_file = NULL;
    return 0;
}
