#ifndef STORAGE_H
#define STORAGE_H

// This file generated by ChatGPT

#include <stdint.h>

#include "sensor.pb.h"
#include "state.pb.h"

/**
 * @brief Creates a CSV file for SensorFrame data at the specified path and
 * writes the header row.
 *
 * @param file_path Path to the SensorFrame CSV file to be created.
 *                  Must be a null-terminated string.
 *
 * @return 0 on success, non-zero on failure.
 */
int create_sensor_csv(const char* file_path);

/**
 * @brief Appends a SensorFrame to the previously created SensorFrame CSV file
 * in CSV format.
 *
 * @param sensor_frame Pointer to the SensorFrame struct to be written.
 *                     Must not be NULL.
 *
 * @return 0 on success, non-zero on failure.
 */
int store_sensor_frame(const SensorFrame* sensor_frame);

/**
 * @brief Closes the SensorFrame CSV file if it's open.
 *        Should be called when done writing to ensure data is flushed and
 * resources are freed.
 *
 * @return 0 on success, non-zero on failure.
 */
int close_sensor_csv(void);

/**
 * @brief Creates a CSV file for StateFrame data at the specified path and
 * writes the header row.
 *
 * @param file_path Path to the StateFrame CSV file to be created.
 *                  Must be a null-terminated string.
 *
 * @return 0 on success, non-zero on failure.
 */
int create_state_csv(const char* file_path);

/**
 * @brief Appends a StateFrame to the previously created StateFrame CSV file in
 * CSV format.
 *
 * @param state_frame Pointer to the StateFrame struct to be written.
 *                    Must not be NULL.
 *
 * @return 0 on success, non-zero on failure.
 */
int store_state_frame(const StateFrame* state_frame);

/**
 * @brief Closes the StateFrame CSV file if it's open.
 *        Should be called when done writing to ensure data is flushed and
 * resources are freed.
 *
 * @return 0 on success, non-zero on failure.
 */
int close_state_csv(void);

/**
 * @brief Creates log files assigned to FDs 3 and 4 to prevent rogue writes from
 * affecting CSV files. The paths to the log files are assumed to be defined via
 * #define elsewhere.
 */
void create_log_files(void);

/**
 * @brief Closes the log files assigned to FDs 3 and 4.
 */
void close_log_files(void);

#endif  // STORAGE_H
