/*
    Board specific definitions such as pin assignments
*/

#ifndef BOARD_H
#define BOARD_H

#include "imxrt1062/MIMXRT1062/gpio_port_map.h"

// Physical pin to gpio base
static GPIO_Type* GPIO_PIN_TO_BASE[] = {
    GPIO_AD_B0_03_BASE, GPIO_AD_B0_02_BASE, GPIO_EMC_04_BASE,
    GPIO_EMC_05_BASE,   GPIO_EMC_06_BASE,   GPIO_EMC_08_BASE,
    GPIO_B0_10_BASE,    GPIO_B1_01_BASE,    GPIO_B1_00_BASE,
    GPIO_B0_11_BASE,    GPIO_B0_00_BASE,    GPIO_B0_02_BASE,
    GPIO_B0_01_BASE,    GPIO_B0_03_BASE,    GPIO_AD_B1_02_BASE,
    GPIO_AD_B1_03_BASE, GPIO_AD_B1_07_BASE, GPIO_AD_B1_06_BASE,
    GPIO_AD_B1_01_BASE, GPIO_AD_B1_00_BASE, GPIO_AD_B1_10_BASE,
    GPIO_AD_B1_11_BASE, GPIO_AD_B1_08_BASE, GPIO_AD_B1_09_BASE,
    GPIO_AD_B0_12_BASE, GPIO_AD_B0_13_BASE, GPIO_AD_B1_14_BASE,
    GPIO_AD_B1_15_BASE, GPIO_EMC_32_BASE,   GPIO_EMC_31_BASE,
    GPIO_EMC_37_BASE,   GPIO_EMC_36_BASE,   GPIO_B0_12_BASE,
    GPIO_EMC_07_BASE,   GPIO_B1_13_BASE,    GPIO_B1_12_BASE,
    GPIO_B1_02_BASE,    GPIO_B1_03_BASE,    GPIO_AD_B1_12_BASE,
    GPIO_AD_B1_13_BASE, GPIO_AD_B1_04_BASE, GPIO_AD_B1_05_BASE,
    GPIO_SD_B0_03_BASE, GPIO_SD_B0_02_BASE, GPIO_SD_B0_01_BASE,
    GPIO_SD_B0_00_BASE, GPIO_SD_B0_05_BASE, GPIO_SD_B0_04_BASE,
    GPIO_EMC_24_BASE,   GPIO_EMC_27_BASE,   GPIO_EMC_28_BASE,
    GPIO_EMC_22_BASE,   GPIO_EMC_26_BASE,   GPIO_EMC_25_BASE,
    GPIO_EMC_29_BASE,
};

// Physical pin to gpio num
static uint8_t GPIO_PIN_TO_NUM[] = {
    GPIO_AD_B0_03_PIN, GPIO_AD_B0_02_PIN, GPIO_EMC_04_PIN,   GPIO_EMC_05_PIN,
    GPIO_EMC_06_PIN,   GPIO_EMC_08_PIN,   GPIO_B0_10_PIN,    GPIO_B1_01_PIN,
    GPIO_B1_00_PIN,    GPIO_B0_11_PIN,    GPIO_B0_00_PIN,    GPIO_B0_02_PIN,
    GPIO_B0_01_PIN,    GPIO_B0_03_PIN,    GPIO_AD_B1_02_PIN, GPIO_AD_B1_03_PIN,
    GPIO_AD_B1_07_PIN, GPIO_AD_B1_06_PIN, GPIO_AD_B1_01_PIN, GPIO_AD_B1_00_PIN,
    GPIO_AD_B1_10_PIN, GPIO_AD_B1_11_PIN, GPIO_AD_B1_08_PIN, GPIO_AD_B1_09_PIN,
    GPIO_AD_B0_12_PIN, GPIO_AD_B0_13_PIN, GPIO_AD_B1_14_PIN, GPIO_AD_B1_15_PIN,
    GPIO_EMC_32_PIN,   GPIO_EMC_31_PIN,   GPIO_EMC_37_PIN,   GPIO_EMC_36_PIN,
    GPIO_B0_12_PIN,    GPIO_EMC_07_PIN,   GPIO_B1_13_PIN,    GPIO_B1_12_PIN,
    GPIO_B1_02_PIN,    GPIO_B1_03_PIN,    GPIO_AD_B1_12_PIN, GPIO_AD_B1_13_PIN,
    GPIO_AD_B1_04_PIN, GPIO_AD_B1_05_PIN, GPIO_SD_B0_03_PIN, GPIO_SD_B0_02_PIN,
    GPIO_SD_B0_01_PIN, GPIO_SD_B0_00_PIN, GPIO_SD_B0_05_PIN, GPIO_SD_B0_04_PIN,
    GPIO_EMC_24_PIN,   GPIO_EMC_27_PIN,   GPIO_EMC_28_PIN,   GPIO_EMC_22_PIN,
    GPIO_EMC_26_PIN,   GPIO_EMC_25_PIN,   GPIO_EMC_29_PIN,
};

// Physical pin to iomuxc base
static uint32_t IOMUXC_PIN_TO_MUX[] = {
    IOMUXC_BASE + ((kIOMUXC_SW_MUX_CTL_PAD_GPIO_AD_B0_03 << 2) + 20),
    IOMUXC_BASE + ((kIOMUXC_SW_MUX_CTL_PAD_GPIO_AD_B0_02 << 2) + 20),
    IOMUXC_BASE + ((kIOMUXC_SW_MUX_CTL_PAD_GPIO_EMC_04 << 2) + 20),
    IOMUXC_BASE + ((kIOMUXC_SW_MUX_CTL_PAD_GPIO_EMC_05 << 2) + 20),
    IOMUXC_BASE + ((kIOMUXC_SW_MUX_CTL_PAD_GPIO_EMC_06 << 2) + 20),
    IOMUXC_BASE + ((kIOMUXC_SW_MUX_CTL_PAD_GPIO_EMC_08 << 2) + 20),
    IOMUXC_BASE + ((kIOMUXC_SW_MUX_CTL_PAD_GPIO_B0_10 << 2) + 20),
    IOMUXC_BASE + ((kIOMUXC_SW_MUX_CTL_PAD_GPIO_B1_01 << 2) + 20),
    IOMUXC_BASE + ((kIOMUXC_SW_MUX_CTL_PAD_GPIO_B1_00 << 2) + 20),
    IOMUXC_BASE + ((kIOMUXC_SW_MUX_CTL_PAD_GPIO_B0_11 << 2) + 20),
    IOMUXC_BASE + ((kIOMUXC_SW_MUX_CTL_PAD_GPIO_B0_00 << 2) + 20),
    IOMUXC_BASE + ((kIOMUXC_SW_MUX_CTL_PAD_GPIO_B0_02 << 2) + 20),
    IOMUXC_BASE + ((kIOMUXC_SW_MUX_CTL_PAD_GPIO_B0_01 << 2) + 20),
    IOMUXC_BASE + ((kIOMUXC_SW_MUX_CTL_PAD_GPIO_B0_03 << 2) + 20),
    IOMUXC_BASE + ((kIOMUXC_SW_MUX_CTL_PAD_GPIO_AD_B1_02 << 2) + 20),
    IOMUXC_BASE + ((kIOMUXC_SW_MUX_CTL_PAD_GPIO_AD_B1_03 << 2) + 20),
    IOMUXC_BASE + ((kIOMUXC_SW_MUX_CTL_PAD_GPIO_AD_B1_07 << 2) + 20),
    IOMUXC_BASE + ((kIOMUXC_SW_MUX_CTL_PAD_GPIO_AD_B1_06 << 2) + 20),
    IOMUXC_BASE + ((kIOMUXC_SW_MUX_CTL_PAD_GPIO_AD_B1_01 << 2) + 20),
    IOMUXC_BASE + ((kIOMUXC_SW_MUX_CTL_PAD_GPIO_AD_B1_00 << 2) + 20),
    IOMUXC_BASE + ((kIOMUXC_SW_MUX_CTL_PAD_GPIO_AD_B1_10 << 2) + 20),
    IOMUXC_BASE + ((kIOMUXC_SW_MUX_CTL_PAD_GPIO_AD_B1_11 << 2) + 20),
    IOMUXC_BASE + ((kIOMUXC_SW_MUX_CTL_PAD_GPIO_AD_B1_08 << 2) + 20),
    IOMUXC_BASE + ((kIOMUXC_SW_MUX_CTL_PAD_GPIO_AD_B1_09 << 2) + 20),
    IOMUXC_BASE + ((kIOMUXC_SW_MUX_CTL_PAD_GPIO_AD_B0_12 << 2) + 20),
    IOMUXC_BASE + ((kIOMUXC_SW_MUX_CTL_PAD_GPIO_AD_B0_13 << 2) + 20),
    IOMUXC_BASE + ((kIOMUXC_SW_MUX_CTL_PAD_GPIO_AD_B1_14 << 2) + 20),
    IOMUXC_BASE + ((kIOMUXC_SW_MUX_CTL_PAD_GPIO_AD_B1_15 << 2) + 20),
    IOMUXC_BASE + ((kIOMUXC_SW_MUX_CTL_PAD_GPIO_EMC_32 << 2) + 20),
    IOMUXC_BASE + ((kIOMUXC_SW_MUX_CTL_PAD_GPIO_EMC_31 << 2) + 20),
    IOMUXC_BASE + ((kIOMUXC_SW_MUX_CTL_PAD_GPIO_EMC_37 << 2) + 20),
    IOMUXC_BASE + ((kIOMUXC_SW_MUX_CTL_PAD_GPIO_EMC_36 << 2) + 20),
    IOMUXC_BASE + ((kIOMUXC_SW_MUX_CTL_PAD_GPIO_B0_12 << 2) + 20),
    IOMUXC_BASE + ((kIOMUXC_SW_MUX_CTL_PAD_GPIO_EMC_07 << 2) + 20),
    IOMUXC_BASE + ((kIOMUXC_SW_MUX_CTL_PAD_GPIO_B1_13 << 2) + 20),
    IOMUXC_BASE + ((kIOMUXC_SW_MUX_CTL_PAD_GPIO_B1_12 << 2) + 20),
    IOMUXC_BASE + ((kIOMUXC_SW_MUX_CTL_PAD_GPIO_B1_02 << 2) + 20),
    IOMUXC_BASE + ((kIOMUXC_SW_MUX_CTL_PAD_GPIO_B1_03 << 2) + 20),
    IOMUXC_BASE + ((kIOMUXC_SW_MUX_CTL_PAD_GPIO_AD_B1_12 << 2) + 20),
    IOMUXC_BASE + ((kIOMUXC_SW_MUX_CTL_PAD_GPIO_AD_B1_13 << 2) + 20),
    IOMUXC_BASE + ((kIOMUXC_SW_MUX_CTL_PAD_GPIO_AD_B1_04 << 2) + 20),
    IOMUXC_BASE + ((kIOMUXC_SW_MUX_CTL_PAD_GPIO_AD_B1_05 << 2) + 20),
    IOMUXC_BASE + ((kIOMUXC_SW_MUX_CTL_PAD_GPIO_SD_B0_03 << 2) + 20),
    IOMUXC_BASE + ((kIOMUXC_SW_MUX_CTL_PAD_GPIO_SD_B0_02 << 2) + 20),
    IOMUXC_BASE + ((kIOMUXC_SW_MUX_CTL_PAD_GPIO_SD_B0_01 << 2) + 20),
    IOMUXC_BASE + ((kIOMUXC_SW_MUX_CTL_PAD_GPIO_SD_B0_00 << 2) + 20),
    IOMUXC_BASE + ((kIOMUXC_SW_MUX_CTL_PAD_GPIO_SD_B0_05 << 2) + 20),
    IOMUXC_BASE + ((kIOMUXC_SW_MUX_CTL_PAD_GPIO_SD_B0_04 << 2) + 20),
    IOMUXC_BASE + ((kIOMUXC_SW_MUX_CTL_PAD_GPIO_EMC_24 << 2) + 20),
    IOMUXC_BASE + ((kIOMUXC_SW_MUX_CTL_PAD_GPIO_EMC_27 << 2) + 20),
    IOMUXC_BASE + ((kIOMUXC_SW_MUX_CTL_PAD_GPIO_EMC_28 << 2) + 20),
    IOMUXC_BASE + ((kIOMUXC_SW_MUX_CTL_PAD_GPIO_EMC_22 << 2) + 20),
    IOMUXC_BASE + ((kIOMUXC_SW_MUX_CTL_PAD_GPIO_EMC_26 << 2) + 20),
    IOMUXC_BASE + ((kIOMUXC_SW_MUX_CTL_PAD_GPIO_EMC_25 << 2) + 20),
    IOMUXC_BASE + ((kIOMUXC_SW_MUX_CTL_PAD_GPIO_EMC_29 << 2) + 20),
};
#endif